[theme]
base="light"
primaryColor="slateBlue"
backgroundColor="white"
secondaryBackgroundColor="lavender"
baseRadius="full"

[theme.sidebar]
backgroundColor="aliceBlue"
secondaryBackgroundColor="lavender"
baseRadius="none"